[build]
  publish = "/"
  command = "echo 'No build command'"

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
  force = true